"""Fix orders, order_items, address models

Revision ID: 75de5c526c03
Revises: 5a9bbb6d0ee6
Create Date: 2025-12-20 19:13:00.556052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75de5c526c03'
down_revision = '5a9bbb6d0ee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_price', sa.Float(), nullable=False))
        batch_op.drop_column('unit_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.FLOAT(), nullable=False))
        batch_op.drop_column('product_price')

    # ### end Alembic commands ###
